### ISSUE TITLE
user rating is taking a simple average, which may not be very effective

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/nyc-accessible-restaurant-advisor#166]
When there are very few reviews on a restaurant, the star ratings may not be representative.

Check this bar that I reviewed twice: http://accessible-nyc-main.herokuapp.com/restaurants/detail/K7c1bkgmmdiTcsQ5afGFNQ

**Comment by rossy312** [comment]
Thanks for the feedback. Although we agree that taking an average can skew the ratings when there are few reviews, after considering the alternatives, we have decided to stick with this approach. Additionally, in the scenario in which a user had both extremely positive and extremely negative experiences at the same restaurant, we would want both of those experiences reflected in the final review (so that it would land somewhere in the middle).

**Comment by jackxujh** [comment]
thanks for sharing the thought behind, @rossy312 ! It makes sense. if the team has time, and feel it is useful, I would also hope to see a tiered sum of 1-5 stars, as a user - but that's up to you of course!
